# Generated by Django 6.0.5 on 2026-05-17 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='niño',
            name='escuela',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='niño',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='niño',
            name='nombre_informante',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='niño',
            name='padre_tutor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='niño',
            name='periodo_conoce_nino',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='niño',
            name='relacion_informante',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
