# Generated by Django 6.0.5 on 2026-05-17 16:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Métricas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('evaluaciones_iniciadas', models.IntegerField(default=0)),
                ('evaluaciones_completadas', models.IntegerField(default=0)),
                ('duración_promedio_minutos', models.IntegerField(blank=True, null=True)),
                ('errores_sistema', models.IntegerField(default=0)),
                ('fallback_activado_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Métrica',
                'verbose_name_plural': 'Métricas',
                'db_table': 'métricas',
            },
        ),
        migrations.CreateModel(
            name='Evaluación',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('psychologist_id', models.UUIDField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('INITIATED', 'Iniciada'), ('IN_PROGRESS', 'En Progreso'), ('COMPLETED', 'Completada'), ('STOPPED', 'Detenida'), ('ARCHIVED', 'Archivada')], default='INITIATED', max_length=20)),
                ('edad_meses', models.IntegerField(blank=True, null=True)),
                ('session_code', models.CharField(max_length=10, unique=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('niño', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='children.niño')),
            ],
            options={
                'verbose_name': 'Evaluación',
                'verbose_name_plural': 'Evaluaciones',
                'db_table': 'evaluaciones',
            },
        ),
        migrations.CreateModel(
            name='Diagnóstico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contenido', models.TextField()),
                ('modelo_ai', models.CharField(max_length=50)),
                ('gdq', models.IntegerField(blank=True, null=True)),
                ('actividades_estimulación', models.JSONField(default=list)),
                ('modificado_por_psicólogo', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluación', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diagnóstico', to='evaluaciones.evaluación')),
            ],
            options={
                'verbose_name': 'Diagnóstico',
                'verbose_name_plural': 'Diagnósticos',
                'db_table': 'diagnósticos',
            },
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('minijuego_id', models.CharField(max_length=100)),
                ('item_id', models.CharField(max_length=50)),
                ('resultado', models.CharField(choices=[('CORRECT', 'Correcto'), ('ERROR', 'Error'), ('NOT_APPLICABLE', 'No Aplica')], max_length=20)),
                ('tiempo_respuesta_ms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluación', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='evaluaciones.evaluación')),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
                'db_table': 'respuestas',
            },
        ),
        migrations.CreateModel(
            name='ResultadoÁrea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('área', models.CharField(max_length=50)),
                ('puntuación_directa', models.IntegerField()),
                ('puntuación_estándar', models.IntegerField(blank=True, null=True)),
                ('percentil', models.IntegerField(blank=True, null=True)),
                ('edad_equivalente', models.CharField(blank=True, max_length=50, null=True)),
                ('cociente_general_gdq', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluación', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='evaluaciones.evaluación')),
            ],
            options={
                'verbose_name': 'Resultado por Área',
                'verbose_name_plural': 'Resultados por Área',
                'db_table': 'resultados_área',
            },
        ),
    ]
