# Generated by Django 6.0.5 on 2026-06-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluación',
            name='psychologist_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
