# Generated by Django 6.0.5 on 2026-06-20 18:10

import django.db.models.deletion
import src.api.evaluaciones.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0002_alter_evaluación_psychologist_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluación',
            name='child_data_completed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='evaluación',
            name='current_area',
            field=models.CharField(default='COGNITIVO', max_length=50),
        ),
        migrations.AddField(
            model_name='evaluación',
            name='current_area_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evaluación',
            name='current_item_id',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='evaluación',
            name='modo_evaluacion',
            field=models.CharField(choices=[('SYNCHRONOUS', 'Sincrónica'), ('DEFERRED', 'Diferida'), ('HYBRID', 'Híbrida')], default='HYBRID', max_length=20),
        ),
        migrations.AddField(
            model_name='evaluación',
            name='preliminary_calculated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evaluación',
            name='session_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evaluación',
            name='session_token',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='evaluación',
            name='validated_calculated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='area',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='final_result',
            field=models.CharField(blank=True, choices=[('PASS', 'Pasó'), ('FAIL', 'No pasó'), ('INCONCLUSIVE', 'Inconcluso'), ('NOT_ADMINISTERED', 'No administrado')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='is_final',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='raw_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='source',
            field=models.CharField(choices=[('SYSTEM_AUTO', 'Sistema automático'), ('SYSTEM_ASSISTED', 'Sistema asistido'), ('CHILD_INTERACTION', 'Interacción del niño'), ('ADULT_ASSISTED', 'Adulto acompañante'), ('PSYCHOLOGIST_REVIEW', 'Revisión del psicólogo')], default='SYSTEM_AUTO', max_length=40),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='validation_status',
            field=models.CharField(choices=[('AUTO_ACCEPTED', 'Aceptada automáticamente'), ('NEEDS_REVIEW', 'Requiere revisión'), ('PSYCHOLOGIST_CONFIRMED', 'Confirmada por psicólogo'), ('PSYCHOLOGIST_CORRECTED', 'Corregida por psicólogo'), ('REJECTED', 'Rechazada'), ('INCONCLUSIVE', 'Inconclusa')], default='NEEDS_REVIEW', max_length=40),
        ),
        migrations.AlterField(
            model_name='evaluación',
            name='estado',
            field=models.CharField(choices=[('INITIATED', 'Iniciada'), ('IN_PROGRESS', 'En Progreso'), ('COMPLETED', 'Completada'), ('STOPPED', 'Detenida'), ('ARCHIVED', 'Archivada'), ('WAITING_CHILD_DATA', 'Esperando datos del niño'), ('WAITING_CONSENT', 'Esperando consentimiento'), ('PENDING_REVIEW', 'Pendiente de revisión'), ('REVIEW_IN_PROGRESS', 'Revisión en progreso'), ('VALIDATED', 'Validada'), ('CANCELLED', 'Cancelada')], default='INITIATED', max_length=20),
        ),
        migrations.CreateModel(
            name='Consentimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('consent_text_version', models.CharField(default='1.0', max_length=20)),
                ('accepted_logs', models.BooleanField(default=True)),
                ('accepted_screenshots', models.BooleanField(default=True)),
                ('accepted_audio', models.BooleanField(default=True)),
                ('accepted_video', models.BooleanField(default=True)),
                ('adult_observation', models.TextField(blank=True)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluación', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consentimiento', to='evaluaciones.evaluación')),
            ],
            options={
                'verbose_name': 'Consentimiento',
                'verbose_name_plural': 'Consentimientos',
                'db_table': 'consentimientos',
            },
        ),
        migrations.CreateModel(
            name='EvaluacionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=80)),
                ('area', models.CharField(max_length=50)),
                ('orden', models.IntegerField(default=0)),
                ('modalidad', models.CharField(choices=[('INTERACTIVO_AUTO', 'Interactivo automático'), ('INTERACTIVO_ASISTIDO', 'Interactivo asistido'), ('EVIDENCIA_DIFERIDA', 'Evidencia diferida'), ('OBSERVACION_FISICA', 'Observación física'), ('PREGUNTA_CUIDADOR', 'Pregunta al cuidador'), ('MANUAL_GUIADO', 'Manual guiado')], default='MANUAL_GUIADO', max_length=40)),
                ('pantalla_nino', models.CharField(default='INSTRUCCION_SIMPLE', max_length=40)),
                ('estado', models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_PROGRESS', 'En progreso'), ('AUTO_VALIDATED', 'Validado automáticamente'), ('NEEDS_REVIEW', 'Requiere revisión'), ('REVIEWED', 'Revisado'), ('INCONCLUSIVE', 'Inconcluso'), ('NOT_ADMINISTERED', 'No administrado')], default='PENDING', max_length=30)),
                ('system_result', models.CharField(blank=True, choices=[('PASS', 'Pasó'), ('FAIL', 'No pasó'), ('INCONCLUSIVE', 'Inconcluso'), ('NOT_ADMINISTERED', 'No administrado')], max_length=30, null=True)),
                ('system_confidence', models.FloatField(blank=True, null=True)),
                ('final_result', models.CharField(blank=True, choices=[('PASS', 'Pasó'), ('FAIL', 'No pasó'), ('INCONCLUSIVE', 'Inconcluso'), ('NOT_ADMINISTERED', 'No administrado')], max_length=30, null=True)),
                ('requires_review', models.BooleanField(default=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('psychologist_notes', models.TextField(blank=True)),
                ('adult_notes', models.TextField(blank=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('attempt_number', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluación', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='evaluaciones.evaluación')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ítem de Evaluación',
                'verbose_name_plural': 'Ítems de Evaluación',
                'db_table': 'evaluacion_items',
            },
        ),
        migrations.AddField(
            model_name='respuesta',
            name='evaluación_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas', to='evaluaciones.evaluacionitem'),
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('LOG', 'Log'), ('TIME_EVENT', 'Evento de tiempo'), ('SCREENSHOT', 'Captura'), ('AUDIO', 'Audio'), ('VIDEO', 'Video'), ('CAMERA_FRAME', 'Frame de cámara'), ('SYSTEM_RESULT', 'Resultado del sistema')], max_length=30)),
                ('file', models.FileField(blank=True, null=True, upload_to=src.api.evaluaciones.models.evidencia_upload_path)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('size_bytes', models.IntegerField(blank=True, null=True)),
                ('captured_by', models.CharField(default='CHILD_DEVICE', max_length=40)),
                ('consent_required', models.BooleanField(default=True)),
                ('is_sensitive', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluación', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='evaluaciones.evaluación')),
                ('evaluación_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='evaluaciones.evaluacionitem')),
            ],
            options={
                'verbose_name': 'Evidencia',
                'verbose_name_plural': 'Evidencias',
                'db_table': 'evidencias',
            },
        ),
        migrations.CreateModel(
            name='InteractionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=80)),
                ('event_payload', models.JSONField(blank=True, default=dict)),
                ('relative_time_ms', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('evaluación', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interaction_events', to='evaluaciones.evaluación')),
                ('evaluación_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interaction_events', to='evaluaciones.evaluacionitem')),
            ],
            options={
                'verbose_name': 'Evento de Interacción',
                'verbose_name_plural': 'Eventos de Interacción',
                'db_table': 'interaction_events',
            },
        ),
        migrations.AddIndex(
            model_name='evaluacionitem',
            index=models.Index(fields=['evaluación', 'area', 'estado'], name='evaluacion__evaluac_f96fc9_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluacionitem',
            index=models.Index(fields=['evaluación', 'item_id'], name='evaluacion__evaluac_2a3341_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='evaluacionitem',
            unique_together={('evaluación', 'item_id', 'attempt_number')},
        ),
        migrations.AddIndex(
            model_name='evidencia',
            index=models.Index(fields=['evaluación', 'type', 'created_at'], name='evidencias_evaluac_b2264e_idx'),
        ),
        migrations.AddIndex(
            model_name='interactionevent',
            index=models.Index(fields=['evaluación', 'event_type', 'timestamp'], name='interaction_evaluac_88e5a3_idx'),
        ),
    ]
