# Generated by Django 6.1 on 2026-09-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0024_telemetry_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='consentrecord',
            name='custodian',
            field=models.CharField(default='DAYC2', max_length=160),
        ),
        migrations.AddField(
            model_name='consentrecord',
            name='device_id',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='consentrecord',
            name='presenter',
            field=models.CharField(default='DAYC2', max_length=160),
        ),
        migrations.AddField(
            model_name='consentrecord',
            name='purpose',
            field=models.CharField(default='DAYC2_EVALUATION', max_length=120),
        ),
        migrations.AddField(
            model_name='consentrecord',
            name='representative',
            field=models.CharField(default='', max_length=160),
        ),
        migrations.AddField(
            model_name='consentrecord',
            name='session_identifier',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='consentrecord',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evidenceasset',
            name='withdrawal_action',
            field=models.CharField(default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='evidenceasset',
            name='withdrawn_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='withdrawal_action',
            field=models.CharField(default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='withdrawn_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrecord',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrecord',
            name='retention_action',
            field=models.CharField(default='ERASED', max_length=20),
        ),
    ]
